export const wishlist = {
    ADD_WISH: 'ADD_WISH',
    ADD_WISH_REQUESTED: 'ADD_WISH_REQUESTED',
    ADD_WISH_SUCCESS: 'ADD_WISH_SUCCESS',
    REMOVE_WISH: 'REMOVE_WISH',
    REMOVE_WISH_REQUESTED: 'REMOVE_WISH_REQUESTED',
    REMOVE_WISH_SUCCESS: 'REMOVE_WISH_SUCCESS',
    INITIALIZE_WISHLIST: 'INITIALIZE_WISHLIST',
    INITIALIZE_WISHLIST_REQUESTED: 'INITIALIZE_WISHLIST_REQUESTED',
    INITIALIZE_WISHLIST_SUCCESS: 'INITIALIZE_WISHLIST_SUCCESS',
}

export const auth = {
    SIGN_IN: 'SIGN_IN',
    SIGN_IN_REQUESTED: 'SIGNIN_REQUESTED',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGNIN_FAILURE: 'SIGNIN_FAILURE',
    SIGN_OUT: 'SING_OUT',
    SIGN_OUT_REQUESTED: 'SIGN_OUT_REQUESTED',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    RESTORE_TOKEN: 'RESTORE_TOKEN',
    RESTORE_TOKEN_REQUESTED: 'RESTORE_TOKEN_REQUESTED',
    RESTORE_TOKEN_SUCCESS: 'RESTORE_TOKEN_SUCCESS',
    RESTORE_TOKEN_FAILURE: 'RESTORE_TOKEN_FAILURE',

}

export const account = {
    RESTORE_ACCOUNT: ' RESTORE_ACCOUNT'
}